=== demoa00/SE2_11_thesis_management/server/json_schema_validator/thesisproposal.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "thesisProposal_schema",
    "title": "Thesis Proposal Schema",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "thesisProposalId": {
            "type": "integer",
            "minimum": 1
        },
        "title": {
            "type": "string",
            "minLength": 1
        },
        "supervisor": {
            "type": "string",
            "pattern": "^(p|P)[0-9]{6}$"
        },
        "coSupervisor": {
            "type": "array",
            "items": {
                "type": "string",
                "pattern": "^((p|P)|(e|E))[0-9]{6}$"
            }
        },
        "keywords": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "minItems": 1
        },
        "thesisType": {
            "type": "object",
            "properties": {
                "inCompany": {
                    "type": "boolean"
                },
                "abroad": {
                    "type": "boolean"
                }
            },
            "additionalProperties": false,
            "required": [
                "inCompany",
                "abroad"
            ]
        },
        "groups": {
            "type": "array",
            "items": {
                "type": "string",
                "minLength": 1
            },
            "minItems": 1
        },
        "description": {
            "type": "string",
            "minLength": 1,
            "maxLength": 1000
        },
        "requirements": {
            "type": "string",
            "minLength": 1,
            "maxLength": 1000
        },
        "notes": {
            "type": "string",
            "minLength": 1,
            "maxLength": 1000
        },
        "expirationDate": {
            "type": "string",
            "format": "date"
        },
        "level": {
            "enum": [
                "BSc",
                "MSc"
            ]
        },
        "CdS": {
            "type": "array",
            "items": {
                "type": "string",
                "minLength": 1
            },
            "minItems": 1
        },
        "isArchieved": {
            "type": "boolean",
            "default": false
        }
    },
    "additionalProperties": false,
    "required": [
        "title",
        "keywords",
        "thesisType",
        "description",
        "requirements",
        "expirationDate",
        "level",
        "CdS"
    ]
}

=== demoa00/SE2_11_thesis_management/json_schema/test/test_thesisproposal_schema.json
{
    "$schema": "../thesisproposal.json",
    "thesisProposalId": 1,
    "title": "Research in Computer Science",
    "supervisor": "p123456",
    "coSupervisor": [
        "p789632",
        "e123456"
    ],
    "keywords": [
        "company"
    ],
    "notes": "Nothing",
    "thesisType": {
        "inCompany": false,
        "abroad": false
    },
    "groups": [
        "AI-group"
    ],
    "description": "Beautiful thesis",
    "requirements": "C",
    "expirationDate": "2025-12-01",
    "level": "MSc",
    "CdS": [
        "Computer science"
    ],
    "isArchieved": false
}
